# KPMG arXiv Data Collection

## Task 2.1 - Collect Sample arXiv Data

##Pull a sample of cs.AI paper metadata and PDFs from arXiv for exploratory data analysis.

In [1]:
%pip install arxiv pandas pymupdf -q

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import arxiv
import pandas as pd

In [3]:
client = arxiv.Client()

search = arxiv.Search(
    query="cat:cs.AI",
    max_results=100,
    sort_by=arxiv.SortCriterion.SubmittedDate,
    sort_order=arxiv.SortOrder.Descending
)

results = list(client.results(search))

print("Papers collected:", len(results))

Papers collected: 100

In [4]:
papers = []
for paper in results:
    papers.append({
        "arxiv_id": paper.entry_id.split("/")[-1],
        "title": paper.title,
        "authors": ", ".join(author.name for author in paper.authors),
        "abstract": paper.summary,
        "categories": ", ".join(paper.categories),
        "published": paper.published,
        "updated": paper.updated,
        "pdf_url": paper.pdf_url
    })

In [5]:
df = pd.DataFrame(papers)
df.head()

,arxiv_id,title,authors,abstract,categories,published,updated,pdf_url
0,2609.31619v1,Learning to Stop without Learning to Stop: Sel...,"Parsa Hosseini, Akasha Tigalappanavara, Sumit ...",Reasoning models often generate very long reas...,"cs.AI, cs.CL, cs.LG",2026-09-25 17:59:52+00:00,2026-09-25 17:59:52+00:00,https://arxiv.org/pdf/2609.31619v1
1,2609.31607v1,Statistical attribute alignment for black-box ...,"Kevin Jiang, Morgane Austern, Edgar Dobriban, ...","Generative AI systems are increasingly used, b...","stat.ME, cs.AI, cs.LG, math.ST",2026-09-25 17:55:49+00:00,2026-09-25 17:55:49+00:00,https://arxiv.org/pdf/2609.31607v1
2,2609.31587v1,Compact Documentation for Coding Agents: A Ben...,"Md Shohel Arman, Igor Molybog",We investigate whether natural-language docume...,"cs.SE, cs.AI, cs.CL",2026-09-25 17:42:22+00:00,2026-09-25 17:42:22+00:00,https://arxiv.org/pdf/2609.31587v1
3,2609.31572v1,OC-GS: Gaussian Splatting for Irregular Turnta...,"Jae Joong Lee, Bedrich Benes",Uneven rotation and dropped frames make equal-...,"cs.CV, cs.AI",2026-09-25 17:35:05+00:00,2026-09-25 17:35:05+00:00,https://arxiv.org/pdf/2609.31572v1
4,2609.31569v1,Adapting for AI: How elementary teachers adjus...,"Fasika Melese, Ruiyang Wu, Xinyue Cui, Joanna ...",Conversational AI tools are entering children'...,"cs.HC, cs.AI",2026-09-25 17:33:47+00:00,2026-09-25 17:33:47+00:00,https://arxiv.org/pdf/2609.31569v1

In [6]:
df.shape

(100, 8)

In [7]:
import os

os.makedirs("../data/metadata", exist_ok=True)

csv_path = "../data/metadata/arxiv_csAI_100_metadata.csv"
df.to_csv(csv_path, index=False)

print("Metadata saved successfully.")

Metadata saved successfully.

## Download PDF Sample

Download a smaller sample of arXiv PDFs for paper-length and text-extractability analysis.

In [8]:
pdf_dir = "../data/pdfs"
os.makedirs(pdf_dir, exist_ok=True)

In [9]:
pdf_sample = results[:25]
print("PDFs selected:", len(pdf_sample))

PDFs selected: 25

In [10]:
import urllib.request

for i, paper in enumerate(pdf_sample, start=1):

    arxiv_id = paper.entry_id.split("/")[-1]
    filename = arxiv_id + ".pdf"
    file_path = os.path.join(pdf_dir, filename)

    urllib.request.urlretrieve(paper.pdf_url, file_path)

    print("Downloaded", i, "of", len(pdf_sample))

Downloaded 1 of 25
Downloaded 2 of 25
Downloaded 3 of 25
Downloaded 4 of 25
Downloaded 5 of 25
Downloaded 6 of 25
Downloaded 7 of 25
Downloaded 8 of 25
Downloaded 9 of 25
Downloaded 10 of 25
Downloaded 11 of 25
Downloaded 12 of 25
Downloaded 13 of 25
Downloaded 14 of 25
Downloaded 15 of 25
Downloaded 16 of 25
Downloaded 17 of 25
Downloaded 18 of 25
Downloaded 19 of 25
Downloaded 20 of 25
Downloaded 21 of 25
Downloaded 22 of 25
Downloaded 23 of 25
Downloaded 24 of 25
Downloaded 25 of 25

In [12]:
pdf_files = [
    paper.entry_id.split("/")[-1] + ".pdf"
    for paper in pdf_sample
]

print("PDFs selected for analysis:", len(pdf_files))

PDFs selected for analysis: 25

## Task 2.2 - Explore Metadata
Inspect the metadata fields, data types, and example values.

In [13]:
df.info()
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   arxiv_id    100 non-null    str
 1   title       100 non-null    str
 2   authors     100 non-null    str
 3   abstract    100 non-null    str
 4   categories  100 non-null    str
 5   published   100 non-null    datetime64[us, UTC]
 6   updated     100 non-null    datetime64[us, UTC]
 7   pdf_url     100 non-null    str
dtypes: datetime64[us, UTC](2), str(6)
memory usage: 6.4 KB

,arxiv_id,title,authors,abstract,categories,published,updated,pdf_url
0,2609.31619v1,Learning to Stop without Learning to Stop: Sel...,"Parsa Hosseini, Akasha Tigalappanavara, Sumit ...",Reasoning models often generate very long reas...,"cs.AI, cs.CL, cs.LG",2026-09-25 17:59:52+00:00,2026-09-25 17:59:52+00:00,https://arxiv.org/pdf/2609.31619v1
1,2609.31607v1,Statistical attribute alignment for black-box ...,"Kevin Jiang, Morgane Austern, Edgar Dobriban, ...","Generative AI systems are increasingly used, b...","stat.ME, cs.AI, cs.LG, math.ST",2026-09-25 17:55:49+00:00,2026-09-25 17:55:49+00:00,https://arxiv.org/pdf/2609.31607v1
2,2609.31587v1,Compact Documentation for Coding Agents: A Ben...,"Md Shohel Arman, Igor Molybog",We investigate whether natural-language docume...,"cs.SE, cs.AI, cs.CL",2026-09-25 17:42:22+00:00,2026-09-25 17:42:22+00:00,https://arxiv.org/pdf/2609.31587v1
3,2609.31572v1,OC-GS: Gaussian Splatting for Irregular Turnta...,"Jae Joong Lee, Bedrich Benes",Uneven rotation and dropped frames make equal-...,"cs.CV, cs.AI",2026-09-25 17:35:05+00:00,2026-09-25 17:35:05+00:00,https://arxiv.org/pdf/2609.31572v1
4,2609.31569v1,Adapting for AI: How elementary teachers adjus...,"Fasika Melese, Ruiyang Wu, Xinyue Cui, Joanna ...",Conversational AI tools are entering children'...,"cs.HC, cs.AI",2026-09-25 17:33:47+00:00,2026-09-25 17:33:47+00:00,https://arxiv.org/pdf/2609.31569v1

In [14]:
categories = df["categories"].str.split(", ").explode()

print("Number of unique categories:", categories.nunique())
print("Categories:", sorted(categories.unique()))

Number of unique categories: 33
Categories: ['cond-mat.mtrl-sci', 'cs.AI', 'cs.CL', 'cs.CR', 'cs.CV', 'cs.DB', 'cs.DC', 'cs.DL', 'cs.ET', 'cs.HC', 'cs.IR', 'cs.IT', 'cs.LG', 'cs.MA', 'cs.MM', 'cs.NE', 'cs.NI', 'cs.OS', 'cs.RO', 'cs.SD', 'cs.SE', 'econ.GN', 'eess.AS', 'eess.IV', 'math.ST', 'q-fin.CP', 'q-fin.GN', 'q-fin.RM', 'q-fin.TR', 'quant-ph', 'stat.AP', 'stat.ME', 'stat.ML']

### Category findings
The sample contains 100 papers spanning 33 unique category labels.
Papers can have multiple categories, stored as comma-separated text.
These labels could help the research agent filter papers by topic.

In [15]:
print("Earliest submission:", df["published"].min())
print("Latest submission:", df["published"].max())

Earliest submission: 2026-09-25 07:56:03+00:00
Latest submission: 2026-09-25 17:59:52+00:00

### Submission-date findings
All 100 sampled papers were submitted on September 25, 2026.
The sample covers a narrow time period, so it cannot show trends
across multiple days or months.

### Metadata Field Summary

The dataset contains 100 papers and 8 metadata fields.

| Field | Stored as | Purpose in the research agent |
|---|---|---|
| arxiv_id | Text | Identifies the paper and its version; links metadata to its PDF |
| title | Text | Shows the paper's name in search results |
| authors | Comma-separated text | Identifies who wrote the paper for attribution |
| abstract | Text | Provides a short description that can help find relevant papers |
| categories | Comma-separated text | Allows filtering papers by research topic |
| published | UTC date and time | Allows filtering papers by submission date |
| updated | UTC date and time | Records when the paper was last updated |
| pdf_url | Text | Provides the link for downloading the paper |

### Findings and Limitations

- All 8 fields have 100 non-null values. The six text fields also contain no empty or whitespace-only values.
- The sample contains 33 unique category labels, and papers can have multiple labels.
- All sampled papers were submitted on September 25, 2026.
- This narrow date range cannot show trends over time.
- Category labels should be separated before filtering or counting individual topics.

In [16]:
text_columns = df.select_dtypes(include=["str", "object"])

blank_counts = text_columns.apply(
    lambda column: column.str.strip().eq("").sum()
)

print(blank_counts)

arxiv_id      0
title         0
authors       0
abstract      0
categories    0
pdf_url       0
dtype: int64

In [17]:
for title in df["title"].head(10):
    print(title)
    print()

Learning to Stop without Learning to Stop: Self-Supervised Confidence Training Improves Reasoning Efficiency

Statistical attribute alignment for black-box generative AI via output post-processing

Compact Documentation for Coding Agents: A Benchmark, an Optimizer, and Why It Does Not Transfer

OC-GS: Gaussian Splatting for Irregular Turntable Capture

Adapting for AI: How elementary teachers adjust their practices for an AI-integrated curriculum

DeepEdu-v1: Efficient and Scalable Agentic LLMs for Vietnamese Education

Multi-agent Scaling Across Disjunctive and Compensatory Tasks

A Flow Matching Framework for Neural Representational Dissimilarity

Can You Check That? The Checkability Boundary for Local LLM Network Automation

ClearGS: Reliability-Aware Gaussian Splatting from Handheld Videos

### Title inspection
The first 10 titles are readable, with no obvious text corruption.
They vary in length and describe different research topics.
Titles can help users identify papers in search results.
This check covers only the first 10 titles.